In [1]:
!pip install numpy


   ---------------------------------------- 0.0/12.9 MB ? eta -:--:--
   ------------ --------------------------- 3.9/12.9 MB 29.4 MB/s eta 0:00:01
   ---------------------------------------- 12.9/12.9 MB 35.1 MB/s eta 0:00:00



[notice] A new release of pip is available: 25.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
import numpy as np

## create an array using numpy
 
# create a 1D array

arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [ ]:
#2d array

arr2 = np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [12]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [13]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
# identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
arr = np.array([[1,2,3], [4,5,6]])

print("Array:\n", arr)
print("shape:", arr.shape) #output: (2,3)
print("Number of dimentions: ", arr.ndim) # output: 2
print("size (number of elements):", arr.size) #output: 6
print("Data type:", arr.dtype) #output: int 64
print("Item size (in bytes):", arr.itemsize) # output: 8


Array:
 [[1 2 3]
 [4 5 6]]
shape: (2, 3)
Number of dimentions:  2
size (number of elements): 6
Data type: int64
Item size (in bytes): 8
