In [1]:
!pip install numpy


   ---------------------------------------- 0.0/12.9 MB ? eta -:--:--
   ------------ --------------------------- 3.9/12.9 MB 29.4 MB/s eta 0:00:01
   ---------------------------------------- 12.9/12.9 MB 35.1 MB/s eta 0:00:00



[notice] A new release of pip is available: 25.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
import numpy as np

## create an array using numpy
 
# create a 1D array

arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [ ]:
#2d array

arr2 = np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [12]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [13]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
# identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# attributes of numpy
arr = np.array([[1,2,3], [4,5,6]])

print("Array:\n", arr)
print("shape:", arr.shape) #output: (2,3)
print("Number of dimentions: ", arr.ndim) # output: 2
print("size (number of elements):", arr.size) #output: 6
print("Data type:", arr.dtype) #output: int 64
print("Item size (in bytes):", arr.itemsize) # output: 8


Array:
 [[1 2 3]
 [4 5 6]]
shape: (2, 3)
Number of dimentions:  2
size (number of elements): 6
Data type: int64
Item size (in bytes): 8


In [19]:
### numpy Vectorized operation
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

### element wise addition
print("addition", arr1 + arr2)

### element wise substraction
print('substraction', arr2 - arr1)

### element wise multiplication
print('multiplication', arr1 * arr2)

### element wise division
print('division', arr1 / arr2)

addition [11 22 33 44 55]
substraction [ 9 18 27 36 45]
multiplication [ 10  40  90 160 250]
division [0.1 0.1 0.1 0.1 0.1]


In [20]:
# universal Function
arr = np.array([2,3,4,5,6])

## square root
print(np.sqrt(arr))

## exponential
print(np.exp(arr))

## sine
print(np.sin(arr))

## natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [ ]:
## array slicing and indexing

arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print('Array : \n', arr)

Array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [32]:
print(arr[0][0])
print(arr[0:2, 1:])

1
[[2 3 4]
 [6 7 8]]


In [28]:
arr[1:, 2:]

array([[ 7,  8],
       [11, 12]])

In [33]:
## modift array elements
arr[0,0] = 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [35]:
arr[1:] = 100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [ ]:
### statistical concepts -- Normalization

## to have a mean of 0 and standard derivation of 1 

data = np.array([1,2,3,4,5])

## calculate the mean and standard deviation
mean = np.mean(data)
std_data = np.std(data)

## normalize the data
normalize_data = (data - mean) / std_data
print("normalize data:", normalize_data)

## output:
# normalize data: -1.41421356 -0.70710678  0. 0.70710678  1.41421356]]

normalize data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [38]:
data = np.array([1,2,3,4,5,6,7,8,9,10])

# Mean
mean = np.mean(data)
print('Mean:', mean)

# median
median = np.median(data)
print('Median:', median)

# Standard deviation
std_dev = np.std(data)
print('Standard Deviation:', std_data)

# variance
variance = np.var(data)
print('variance:', variance)


Mean: 5.5
Median: 5.5
Standard Deviation: 1.4142135623730951
variance: 8.25


In [40]:
## logical operations

data = np.array([1,2,3,4,5,6,7,8,9,10])

data[data > 5]

array([ 6,  7,  8,  9, 10])